sonarqube_keycloak_saml_keycloak:
  base_url: "https://{{ groups['keycloak'][0] }}"
  admin_user: "{{ vault_KEYCLOAK_ADMIN_USERNAME }}"
  admin_password: "{{ vault_KEYCLOAK_ADMIN_PASSWORD }}"
  realm: "sonarqube"