---
# Jenkins-Keycloak SSO Integration Handlers

- name: restart jenkins
  command: /bin/systemctl restart jenkins
  delegate_to: "{{ groups['jenkins'][0] }}"
  become: yes

- name: restart keycloak
  systemd:
    name: keycloak
    state: restarted
    enabled: yes
  delegate_to: "{{ groups['keycloak'][0] }}"
