---
# SAML Integration Variables for SonarQube-Keycloak
# These variables are referenced by the sonarqube-keycloak-saml role defaults

# SonarQube host resolution from inventory
sonarqube_hostname: "{{ groups['sonarqube'][0] }}"
sonarqube_base_url: "https://{{ sonarqube_hostname }}"

# Keycloak host resolution from inventory
keycloak_hostname: "{{ groups['keycloak'][0] }}"
keycloak_base_url: "https://{{ keycloak_hostname }}"
