---
# SAML Integration Variables for Applications-Keycloak
# These variables are referenced by the SAML integration role defaults

# SonarQube host resolution from inventory
sonarqube_hostname: "{{ groups['sonarqube_servers'][0] }}"
sonarqube_base_url: "https://{{ sonarqube_hostname }}"

# Jenkins host resolution from inventory
jenkins_hostname: "{{ groups['jenkins_servers'][0] }}"
jenkins_base_url: "https://{{ jenkins_hostname }}"

# Nexus host resolution from inventory
nexus_hostname: "{{ groups['nexus_servers'][0] }}"
nexus_base_url: "https://{{ nexus_hostname }}"

# Artifactory host resolution from inventory (on-premises)
artifactory_hostname: "{{ groups['artifactory_servers'][0] }}"
artifactory_base_url: "https://{{ artifactory_hostname }}"
artifactory_api_url: "http://localhost:8080"  # Internal API access
artifactory_admin_user: "{{ vault_artifactory_admin_username }}"
artifactory_admin_password: "{{ vault_artifactory_admin_password }}"

# Keycloak host resolution from inventory
keycloak_hostname: "{{ groups['keycloak'][0] }}"
keycloak_base_url: "https://{{ keycloak_hostname }}"
keycloak_admin_api_url: "https://{{ keycloak_hostname }}"  # Admin API access via HTTPS
