---
# SAML Integration Variables for SonarQube-Keycloak

# SonarQube host resolution from inventory (DNS name for HTTPS proxy)
# Uses first host in sonarqube group for shared references
sonarqube_hostname: "{{ groups['sonarqube'][0] }}"
sonarqube_host_ip: "{{ hostvars[groups['sonarqube'][0]]['ansible_host'] }}"
sonarqube_host_url: "https://{{ sonarqube_hostname }}"

# Keycloak host resolution from inventory
keycloak_hostname: "{{ groups['keycloak'][0] }}"
keycloak_host_ip: "{{ hostvars[groups['keycloak'][0]]['ansible_host'] }}"
keycloak_base_url: "https://{{ keycloak_hostname }}"

# Keycloak admin credentials
sonarqube_keycloak_saml_keycloak_admin_user: "{{ vault_KEYCLOAK_ADMIN_USERNAME }}"
sonarqube_keycloak_saml_keycloak_admin_password: "{{ vault_KEYCLOAK_ADMIN_PASSWORD }}"
