---
freeipa_setup_server: false
freeipa_setup_dns: false
freeipa_dns_auto_forwarders: true

# Example values; set via vault in production
freeipa_realm: "EXAMPLE.LOCAL"
freeipa_domain: "example.local"
# freeipa_ds_password: "{{ vault_freeipa_ds_password }}"
# freeipa_admin_password: "{{ vault_freeipa_admin_password }}"
