---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: nginx-rocky9
    image: geerlingguy/docker-rockylinux9-ansible:latest
    pre_build_image: true
    privileged: true
    command: /lib/systemd/systemd
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    capabilities:
      - SYS_ADMIN
    networks:
      - name: nginx-test-net
    published_ports:
      - "80:80/tcp"
      - "443:443/tcp"
  - name: jenkins-backend-mock
    image: nginx:alpine
    command: sh -c "echo 'Jenkins Mock Backend' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"
    published_ports:
      - "8080:80/tcp"
    networks:
      - name: nginx-test-net

provisioner:
  name: ansible
  inventory:
    host_vars:
      nginx-rocky9:
        ansible_user: root
        jenkins_backend_host: jenkins-backend-mock
        jenkins_backend_port: 80

verifier:
  name: testinfra

scenario:
  name: default
  test_sequence:
    - dependency
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy