---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: jenkins-rocky9
    image: geerlingguy/docker-rockylinux9-ansible:latest
    pre_build_image: true
    privileged: true
    command: /lib/systemd/systemd
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    capabilities:
      - SYS_ADMIN
    networks:
      - name: jenkins-test-net
    published_ports:
      - "8080:8080/tcp"

provisioner:
  name: ansible
  inventory:
    host_vars:
      jenkins-rocky9:
        ansible_user: root

verifier:
  name: testinfra

scenario:
  name: default
  test_sequence:
    - dependency
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy