---
- name: Prepare
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Install systemd and other required packages
      dnf:
        name:
          - systemd
          - python3
          - python3-pip
          - procps-ng
          - glibc-langpack-en
        state: present

    - name: Start systemd
      command: systemctl daemon-reload
      changed_when: false
