---
galaxy_info:
  role_name: install_sonarqube
  namespace: jimi_automation
  author: Jimi
  description: Install and configure SonarQube with PostgreSQL on Rocky Linux 9
  license: MIT
  min_ansible_version: 2.9

  platforms:
    - name: EL
      versions:
        - 9

  galaxy_tags:
    - sonarqube
    - code-quality
    - static-analysis
    - postgresql
    - rocky
    - rhel

dependencies: []
