---
- name: SonarQube-Keycloak SAML Integration
  hosts: sonarqube
  become: true
  gather_facts: true

  vars:
    # Override any defaults here if needed
    # Example: Force specific SonarQube host
    # sonarqube:
    #   host: "192.168.201.11"

  roles:
    - sonarqube-keycloak-saml
